version: "3.8"

services:
  ### MHIRA Frontend Container ###########################

  mhira-frontend:
    image: ${REGISTRY_HOST}/mhira-frontend:development
    build: ./mhira-frontend
    restart: unless-stopped
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    tty: true
    networks:
      - frontend

  ### MHIRA Backend Container ###########################

  mhira-backend:
    image: ${REGISTRY_HOST}/mhira-backend:development
    restart: unless-stopped
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    environment:
      - SECRET=${JWT_SECRET}
      - SERVER_PORT=3000
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=${POSTGRES_HOST}
      - TYPEORM_USERNAME=${POSTGRES_USER}
      - TYPEORM_DATABASE=${POSTGRES_DB}
      - TYPEORM_PASSWORD=${POSTGRES_PASSWORD}
      - TYPEORM_PORT=${POSTGRES_PORT}
      - TYPEORM_SYNCHRONIZE=true
      - TYPEORM_LOGGING=true
      - TYPEORM_ENTITIES_DIR=/../**/*.model.{js,ts}
      - TYPEORM_MIGRATIONS_TABLE_NAME=migrations
      - TYPEORM_MIGRATIONS=migration/*.js
      - TYPEORM_MIGRATIONS_DIR=src/migrations
      - CACHE_STORE=redis
      - REDIS_HOST=redis
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - SUPERADMIN_USERNAME=${SUPERADMIN_USERNAME}
      - SUPERADMIN_PASSWORD=${SUPERADMIN_PASSWORD}
    tty: true
    networks:
      - frontend
      - backend
    depends_on:
      - redis
      - postgres
      - mongo

  ### Caddy Server Container ##################################

  caddy:
    build: ./caddy
    restart: unless-stopped
    environment:
      - SITE_DOMAIN=${SITE_DOMAIN}
    volumes:
      - ${CADDY_CUSTOM_CADDYFILE}:/etc/caddy/Caddyfile
      - ${CADDY_HOST_LOG_PATH}:/var/log/caddy
      - ${DATA_SAVE_PATH}:/root/.caddy
    ports:
      - "${CADDY_HOST_HTTP_PORT}:80"
      - "${CADDY_HOST_HTTPS_PORT}:443"
    depends_on:
      - mhira-frontend
      - mhira-backend
    networks:
      - frontend
      - backend

  ### PostgreSQL Container ####################################

  postgres:
    build: ./postgres
    restart: unless-stopped
    volumes:
      - ${DATA_SAVE_PATH}/postgres/data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend

  ### MongoDB Container #######################################

  mongo:
    build: ./mongo
    restart: unless-stopped
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - ${DATA_SAVE_PATH}/mongo:/data/db
    networks:
      - backend

  ### Redis Container #########################################

  redis:
    build: ./redis
    restart: unless-stopped
    volumes:
      - ${DATA_SAVE_PATH}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

### Volumes Setup #############################################

volumes:
  postgres:
    driver: "local"
  redis:
    driver: "local"
  mongo:
    driver: "local"
